version: '3.3'
services:
 api:
  build: 
    context: api
  image: flask:3.6
  container_name: tamam-api
  ports:
   - "4000:4000"
  volumes:
   - ./api:/api
   
 database:
  image: mongo:latest
  volumes:
   - ./mongo:/data/db
  container_name: tamam-db