version: '3.3'
services:
 
    
 database:
  image: mongo:4.0.8
  volumes:
   - ./mongo:/data/db
  container_name: tamam-db
  restart: unless-stopped
  command: mongod --auth
  environment:
    MONGO_INITDB_ROOT_USERNAME: mongodbuser
    MONGO_INITDB_ROOT_PASSWORD: thisisanotherverystrongpassword
    MONGO_INITDB_DATABASE: flaskdb
    MONGODB_DATA_DIR: /data/db
    MONDODB_LOG_DIR: /dev/null
    
 media:
  image: kurento/kurento-media-server:latest
  volumes:
    - ./media:/data/media
  container_name: tamam-mcu
  expose:
    - "8888"
  ports:
    - "8888:8888"
    - "4000-5100:4000-5100/udp"
  

 api:
  build: 
    context: api
  image: flask:3.6
  container_name: tamam-api
  ports:
   - "4000:5000"
  volumes:
   - ./api:/api
  restart: always
  environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5001
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: thisisaverystrongpasswordwew
      MONGODB_HOSTNAME: tamam-db
      KURENTO_URI: ws://0.0.0.0:8888/kurento
  depends_on:
   - database
   - media
  links:
   - "media:kms"
   
   

 

  