# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tamam-aub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://tamam.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_59e66679d8de4b23aab6559ac05c8c24 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d015208e14a4e5aa14dc6eaff1e132e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: tamam.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_59e66679d8de4b23aab6559ac05c8c24 }}/tamam-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tamam-aub'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de964008ffc4481084b96030999b086b }}
        images: 'tamam.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_59e66679d8de4b23aab6559ac05c8c24 }}/tamam-api:${{ github.sha }}'